server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1KB
      max-request-size: 1KB
  profiles:
    active: local
    include:
      - domain
      - thirdparty
      - jwt
      - cloud
      - rds

