springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  paths-to-match:
    - /api/**
